---
- name: Download wordpress from link
  hosts: all
  become: yes
  become_method: sudo

  tasks:
    - name: Download wordpress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress
  
    - name: Extract the file
      unarchive:
          src: /tmp/wordpress*
          #format: gzip
          dest: /tmp/
          remote_src: yes
          

    
          